name: Deploy Code to Dev

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{secrets.CLIENTSECRET}}
      
      - name: Deploy to Azure Web App
        uses: Azure/webapps-deploy@v2
        with:
          app-name: 37us6ullbh7fe-dev
          images: 37us6ullbh7fewthreg.azurecr.io/wth/dotnetcoreapp:6
