# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CI

#add variables called registryName repositoryName and imageName
env:
  registryName: '37us6ullbh7fewthreg.azurecr.io'
  repositoryName: 'wth/dotnetcoreapp'
  dockerFolderPath: 'Application/src/RazorPagesTestSample'
  tag: ${{github.run_number}}

on:
  push:
    branches: [ "main" ]
    paths:
      - 'Application/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Application/**'
    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
    - name: Build
      run: dotnet build --no-restore --configuration Release ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj
    - name: Test
      run: dotnet test --no-build --verbosity normal ./Application/tests/RazorPagesTestSample.Tests/RazorPagesTestSample.Tests.csproj

  dockerDeployment:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Docker Login
      run: docker login ${{env.registryName}} -u ${{secrets.ACR_USERNAME}} -p ${{secrets.ACR_PASSWORD}}

    - name: Docker Build
      run: docker build -t $registryName/$repositoryName:$tag --build-arg build_version=$tag $dockerFolderPath

    - name: Docker Push
      run: docker push $registryName/$repositoryName:$tag

  DeployImagetoDev:
    runs-on: ubuntu-latest
    needs: dockerDeployment
    steps:  
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{secrets.CLIENTSECRET}}
    
    - name: Deploy to Azure Web App
      uses: Azure/webapps-deploy@v2
      with:
        app-name: 37us6ullbh7fe-dev
        images: 37us6ullbh7fewthreg.azurecr.io/wth/dotnetcoreapp:${{github.run_number}}

  DeployImagetoTest:
    runs-on: ubuntu-latest
    needs: DeployImagetoDev
    steps:  
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{secrets.CLIENTSECRET}}

    - uses: trstringer/manual-approval@v1
      with:
        secret: ${{ github.TOKEN }}
        approvers: wth-team2
        minimum-approvals: 1
        issue-title: "Deploying v1.3.5 to prod from staging"
        issue-body: "Please approve or deny the deployment of version v1.3.5."
          
    - name: Deploy to Azure Web App
      uses: Azure/webapps-deploy@v2
      with:
        app-name: 37us6ullbh7fe-dev
        images: 37us6ullbh7fewthreg.azurecr.io/wth/dotnetcoreapp:${{github.run_number}}
