name: Deploy

on:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{secrets.CLIENTSECRET}}

      - name: Deploy Bicep
        uses: azure/arm-deploy@v1
        with:
          scope: 'resourcegroup'
          resourceGroupName: ${{vars.RESOURCEGROUP}}
          template: './infrastructureascode/main.bicep'
          deploymentmode: 'Incremental'