name: First Workflow

on:
  push:
    branches:
      - main

jobs:
  step-1:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: echo "This is Step 1"
        
      - name: Step 2
        run: echo "This is Step 2"